dekko-master:
  script:
    - if [ ! -d "__build" ]; then mkdir __build; fi
    - cd __build
    - cmake -DCMAKE_BUILD_TYPE=Release ../
    - make -j2
    - make DESTDIR=./test install
    
  cache:
    paths:
      - __build
  only:
    - master
  artifacts:
    paths:
      - __build/test
      
dekko-feature-branch:
  script:
    - if [ ! -d "build" ]; then mkdir build; fi
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ../
    - make
    - make DESTDIR=./test install
  only:
    - branches@dpniel/Dekko
  except:
    - master@dpniel/Dekko
  cache:
    paths:
      - build
  artifacts:
    paths:
      - build/test