wiki:
  stage: deploy
  tags:
    - armhf
    - no-build
    - trusty
  script:
    - sshpass -e scp -oStrictHostKeyChecking=no -vr $PWD/docs/dev dekkoproject.org@ssh.dekkoproject.org:/www
  only:
    - master

doxygen:
  stage: deploy
  tags:
    - armhf
    - no-build
    - trusty
  script:
    - doxygen Doxyfile
    - mv ../doxygen-out/html ../doxygen-out/docs
    - sshpass -e scp -oStrictHostKeyChecking=no -vr $PWD/../doxygen-out/docs dekkoproject.org@ssh.dekkoproject.org:/www
    - rm -rf ../doxygen-out
  only:
    - master
      
click:amd64:
  stage: build
  tags:
    - amd64
    - xenial
    - sdk-ready
  script:
    - gitman install --depth=1
    - if [ ! -d "__build" ]; then mkdir __build; fi
    - cd __build
    - cmake -G Ninja -DUNITY8=On -DCLICK_MODE=On -DCMAKE_BUILD_TYPE=Release ../
    - ninja -j3
    - export DESTDIR=./test
    - ninja -j3 install
    - cd ./test
    - click build .
  cache:
    paths:
      - __build
  only:
    - master
  artifacts:
    paths:
      - __build/test
    expire_in: 7d
