stages:
  - clickbuild
  
variables:
  GIT_SUBMODULE_STRATEGY: normal
  
click_armhf:
  stage: clickbuild
  tags:
    - click
    - armhf
  script:
    # - ./setup-click-env
    - ./build-click
  cache:
    paths:
      - Qt/
      - .build/
  artifacts:
    paths:
      - '*.click'
    when: on_success
    expire_in: 1 week
