job1:
  script:
    - if [ ! -d "__build" ]; then mkdir __build; fi
    - cd __build
    - cmake -DCMAKE_BUILD_TYPE=Release ../
    - make -j2
    - make DESTDIR=./test install
    
  artifacts:
    paths:
      - __build/test