dekko-master:amd64:
  image: dpniel/dekko-docker-sdk:latest
  tags:
    - scaleway
  script:
    - if [ ! -d "__build" ]; then mkdir __build; fi
    - cd __build
    - cmake -DCMAKE_BUILD_TYPE=Release ../
    - make -j2
    - make DESTDIR=./test install
  cache:
    paths:
      - __build
  only:
    - master
  artifacts:
    paths:
      - __build/test
      
dekko-master:armhf:
  tags:
    - armhf
    - pi
    - click
  script:
    - if [ ! -d "__build" ]; then mkdir __build; fi
    - cd __build
    - cmake -DCMAKE_BUILD_TYPE=Release ../
    - make -j2
    - make DESTDIR=./test install
  cache:
    paths:
      - __build
  only:
    - master
  artifacts:
    paths:
      - __build/test
      
upload-wiki:
  tags:
    - armhf
    - pi
    - click
  script:
    - sshpass -e scp -oStrictHostKeyChecking=no -vr $PWD/docs/dev-wiki dekkoproject.org@ssh.dekkoproject.org:/www
  only:
    - master
      
dekko-feature-branch:
  image: dpniel/dekko-docker-sdk:latest
  tags:
    - scaleway
  script:
    - if [ ! -d "build" ]; then mkdir build; fi
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Debug ../
    - make -j4
    - make DESTDIR=./test install
  only:
    - branches@dpniel/Dekko
  except:
    - master@dpniel/Dekko
  artifacts:
    paths:
      - build/test