stages:
  - clickbuild
  
click_armhf:
  stage: clickbuild
  tags:
    - click
    - armhf
  script:
    - ./setup-click-env
    - ./build-click
  cache:
    paths:
      - Qt/
  artifacts:
    paths:
      - '*.click'
    when: on_success
    expire_in: 1 week
