stages:
  - clickbuild
  
click_armhf:
  stage: clickbuild
  tags:
    - dekko
    - click
  script:
    - ls
    - sudo click chroot -a armhf -f ubuntu-sdk-15.04 -n click maint /opt/dekko/bin/qbs config --list