# This file is a template, and might need editing before it works on your project.
# Official docker image.
#image: registry.dekkoproject.org/docker/snapcraft:overlay

#build:
#  stage: build
#  tags:
#    - docker
#  script:
#    - snapcraft stage
#    - snapcraft prime
#    - snapcraft snap
