upload-wiki:
  tags:
    - armhf
    - no-build
    - trusty
  script:
    - sshpass -e scp -oStrictHostKeyChecking=no -vr $PWD/docs/dev dekkoproject.org@ssh.dekkoproject.org:/www
  only:
    - master
    
upload-docs:
  tags:
    - armhf
    - no-build
    - trusty
  script:
    - doxygen Doxyfile
    - mv ../doxygen-out/html ../doxygen-out/docs
    - sshpass -e scp -oStrictHostKeyChecking=no -vr $PWD/../doxygen-out/docs dekkoproject.org@ssh.dekkoproject.org:/www
    - rm -rf ../doxygen-out
  only:
    - master

dekko-master-click:armhf:
  tags:
    - armhf
    - xenial
    - sdk-ready
    - ninja
  script:
    - git submodule update --init
    - if [ ! -d "__build" ]; then mkdir __build; fi
    - cd __build
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ../
    - ninja -j3
    - export DESTDIR=./test
    - ninja -j3 install
    - cd ./test
    - click build .
  cache:
    paths:
      - __build
  only:
    - master
  artifacts:
    paths:
      - __build/test
      
dekko-master-click:amd64:
  tags:
    - amd64
    - xenial
    - sdk-ready
  script:
    - git submodule update --init
    - if [ ! -d "__build" ]; then mkdir __build; fi
    - cd __build
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ../
    - ninja -j3
    - export DESTDIR=./test
    - ninja -j3 install
    - cd ./test
    - click build .
  cache:
    paths:
      - __build
  only:
    - master
  artifacts:
    paths:
      - __build/test
      
dekko-feature-branch:armhf:
  image: dpniel/dekko-docker-sdk:latest
  tags:
    - armhf
    - xenial
    - sdk-ready
    - ninja
  script:
    - git submodule update --init
    - if [ ! -d "__build" ]; then mkdir __build; fi
    - cd __build
    - cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ../
    - ninja -j3
    - export DESTDIR=./test
    - ninja -j3 install
    - cd ./test
    - click build .
  only:
    - branches@dekko-dev/dekko
  except:
    - master@dekko-dev/dekko
  artifacts:
    paths:
      - __build/test
