location: .gitman
sources:
- name: cmake
  repo: http://code.dekkoproject.org/dekko-dev/cmake-modules.git
  rev: master
  link: cmake
- name: quick-flux
  repo: http://code.dekkoproject.org/dekko-dev/quick-flux.git
  rev: master
  link: plugins/3rdParty/quick-flux
- name: SuperMacros
  repo: http://code.dekkoproject.org/dekko-dev/super-macros.git
  rev: master
  link: lib/3rdParty/SuperMacros
- name: qmf
  repo: http://code.dekkoproject.org/dekko-dev/messagingframework.git
  rev: master
  link: qmf
- name: notify
  repo: http://code.dekkoproject.org/dekko-dev/notify.git
  rev: master
  link: plugins/notify
- name: controls
  repo: http://code.dekkoproject.org/dekko-dev/controls.git
  rev: master
  link: plugins/controls
- name: shared
  repo: http://code.dekkoproject.org/dekko-dev/utils.git
  rev: master
  link: plugins/shared
- name: components
  repo: http://code.dekkoproject.org/dekko-dev/qml-components.git
  rev: master
  link: plugins/components
- name: autoconfig
  repo: http://code.dekkoproject.org/dekko-dev/autoconfig.git
  rev: master
  link: plugins/autoconfig
- name: mail
  repo: http://code.dekkoproject.org/dekko-dev/mail.git
  rev: master
  link: plugins/mail
- name: plugger
  repo:  http://code.dekkoproject.org/dekko-dev/plugger.git
  rev: master
  link: plugins/plugger
- name: maz-db
  repo: http://code.dekkoproject.org/dekko-dev/maz-db.git
  rev: master
  link: plugins/maz-db
