#!/bin/bash

set -e

INSTALL_DIR=$PWD/Qt
QBS_BIN=qbs
DIR_PREFIX=/lib/arm-linux-gnueabihf
BIN_DIR=$DIR_PREFIX/bin
LIB_DIR=$DIR_PREFIX
DATA_DIR=/usr/share/dekko
QML_DIR=$LIB_DIR
PROJECT=/home/ubuntu/Projects/dekko
BUILD_DIR=$PROJECT/.build-armhf
PY_LIBS=$PROJECT/pylibs

function run_cmd {
    lxc exec ubports-cross -- sudo --login --user ubuntu bash -c "$1"
}

function cleanup_pylibs {
    run_cmd "rm -rf $PY_LIBS"
}

function build_xenial {
    run_cmd "cd $PROJECT && \
        $QBS_BIN build \
        -d $BUILD_DIR \
        -f . \
        --clean-install-root \
        --show-progress release \
        project.click:true \
        project.pyotherside:false \
        project.binDir:$BIN_DIR \
        project.libDir:$LIB_DIR \
        project.qmlDir:$QML_DIR \
        project.dataDir:$DATA_DIR \
        profile:dekkoqt5-armhf"
}

function build_vivid {
    run_cmd "cd $PROJECT && \
        $QBS_BIN build \
        -d $BUILD_DIR-xenial \
        -f . \
        --clean-install-root \
        --show-progress release \
        project.click:true \
        project.pyotherside:true \
        project.binDir:$BIN_DIR \
        project.libDir:$LIB_DIR \
        project.qmlDir:$QML_DIR \
        project.dataDir:$DATA_DIR \
        profile:dekkoqt5-armhf"
}


cleanup_pylibs

build_xenial

run_cmd "click build $BUILD_DIR/**/install-root/"

cleanup_pylibs # remove again to ensure we don't mess with host builds
