#! /bin/bash

set -e

qbs build -d ../__dekko_build -f . --clean-install-root debug profile:dekkoqt5
# for click qbs build -d ../__dekko_build -f . --clean-install-root debug project.click:true profile:dekkoqt5

export LD_LIBRARY_PATH=$PWD/../__dekko_build/dekkoqt5-debug/install-root/lib
export QML2_IMPORT_PATH=$LD_LIBRARY_PATH
export QMF_PLUGINS=$LD_LIBRARY_PATH/qmf/plugins5
export DEKKO_PLUGINS=$LD_LIBRARY_PATH/Dekko/plugins

# Location qmf will store the mailstore cache
export QMF_DATA=$HOME/.cache/dekko
# for click export QMF_DATA=$HOME/.cache/dekko2.dekkoproject

echo $0
echo $1

if [ "$1" == "daemon" ]; then
    echo "Starting daemon"
    exec $PWD/../__dekko_build/dekkoqt5-debug/install-root/bin/dekkod
else
    exec $PWD/../__dekko_build/dekkoqt5-debug/install-root/bin/dekko $@
fi
