name: dekko
version: 0.9.7
summary: Dekko email client
description: Fast IMAP e-mail client optimized for mobile
confinement: devmode
grade: devel

apps:
    dekko:
        command: desktop-launch $SNAP/bin/dekko-launch "@"
        plugs:
            - browser-sandbox
            - gsettings
            - home
            - network
            - opengl
            - platform
            - unity7
            - unity8

plugs:
    platform:
        interface: content
        content: ubuntu-app-platform1
        target: ubuntu-app-platform
        default-provider: ubuntu-app-platform
    browser-sandbox:
        interface: browser-support

parts:
    launcher:
        plugin: dump
        source: snap/
        organize:
            dekko.launcher: bin/dekko-launch

    dekko:
        plugin: qbs
        source: "."
        profile: "clang"
        build-variant: "release"
        qt-version: qt5
        build-packages:
            - qttools5-dev-tools
            - libgsettings-qt-dev
            - libconnectivity-qt1-dev
            - libnotify-dev
            - libmessaging-menu-dev
            - libunity-dev
            - libsnappy-dev
            - qtdeclarative5-private-dev
            - qml-module-qtquick-privatewidgets
            - libqt5svg5-dev
        snap:
            - -usr/share/doc
            - -usr/include
        after: [desktop-ubuntu-app-platform]

    pyotherside:
        plugin: qmake
        source: https://github.com/thp/pyotherside.git
        qt-version: qt5
        build-packages:
            - python3-dev
        after: [dekko]

