#! /bin/bash

set -e

BUILD_DIR=${BUILD_DIR:=../__dekko_build}
SRC_DIR=${PWD##*/}

for i in "$@"
do
case $i in
    --devmode)
    DEV_MODE=true
    shift 
    ;;
    --gdb)
    GDB_RUN=true
    shift 
    ;;
    --clean)
    CLEAN=true
    shift 
    ;;
    *)   
    ;;
esac
done

if ! which ninja > /dev/null; then
   echo -e "ninja-build not found! Install it now? (y/n) \c"
   read ninja
   echo "$ninja"
   if [ "$ninja" == "y" ]; then
      sudo apt-get install ninja-build
   else
      echo "This script currently only works with ninja build. either update it to work with gcc make or build it manually :-)"
      exit 1
   fi
fi
if ! which dpkg-architecture > /dev/null; then
   echo -e "dpkg-dev not found! Install it now? (y/n) \c"
   read da
   echo "$da"
   if [ "$da" == "y" ]; then
      sudo apt-get install dpkg-dev
   else
      echo "This script requires dpkg-architecture"
      exit 1
   fi
fi

HOST_ARCH="$(dpkg-architecture -qDEB_HOST_MULTIARCH)"

## Create build dir if it doesn't exist
if [ ! -d "$BUILD_DIR" ]; then
  mkdir ${BUILD_DIR}
fi
# enter it
cd ${BUILD_DIR}

if [ "$CLEAN" = true ]; then
  ninja clean
  exit 0
fi

cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ../${SRC_DIR}
ninja -j3
export DESTDIR=./test
ninja -j3 install

export PATH=$PWD/test/lib/${HOST_ARCH}/bin:$PATH
export LD_LIBRARY_PATH=$PWD/test/lib/${HOST_ARCH}
export QML2_IMPORT_PATH=$PWD/test/lib/${HOST_ARCH}
export QMF_PLUGINS=$PWD/test/lib/${HOST_ARCH}/qmf/plugins5
echo "PATH: $PATH"
echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
echo "QMF_PLUGINS: $QMF_PLUGINS"

if [ "$GDB_RUN" = true ]; then
  gdb ./test/lib/${HOST_ARCH}/bin/dekko
  exit 0
fi

if [ "$DEV_MODE" = true ]; then
  ./test/lib/${HOST_ARCH}/bin/dekko -d $@
else
  ./test/lib/${HOST_ARCH}/bin/dekko $@
fi



