#! /bin/bash

set -e

for i in "$@"
do
case $i in
    --devmode)
    DEV_MODE=true
    shift 
    ;;
    --gdb)
    GDB_RUN=true
    shift 
    ;;
    --clean)
    CLEAN=true
    shift 
    ;;
    *)   
    ;;
esac
done

if [ "$CLEAN" = true ]; then
  ninja clean
  exit 0
fi

cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug ../../dekko2/
ninja -j3
export DESTDIR=./test
ninja -j3 install

export PATH=$PWD/test/lib/x86_64-linux-gnu/bin:$PATH
export LD_LIBRARY_PATH=$PWD/test/lib/x86_64-linux-gnu
export QML2_IMPORT_PATH=$PWD/test/lib/x86_64-linux-gnu
export QMF_PLUGINS=$PWD/test/lib/x86_64-linux-gnu/qmf/plugins5
export OXIDE_DISABLE_SETUID_SANDBOX=1
echo "PATH: $PATH"
echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
echo "QMF_PLUGINS: $QMF_PLUGINS"

if [ "$GDB_RUN" = true ]; then
  gdb ./test/lib/x86_64-linux-gnu/bin/dekko
  exit 0
fi

if [ "$DEV_MODE" = true ]; then
  ./test/lib/x86_64-linux-gnu/bin/dekko -d $@
else
  ./test/lib/x86_64-linux-gnu/bin/dekko $@
fi



