macro(sub_dir_list result curdir)
  file(GLOB children RELATIVE ${curdir} ${curdir}/*)
  set(dirlist "")
  foreach(child ${children})
    if(IS_DIRECTORY ${curdir}/${child})
      list(APPEND dirlist ${child})
    endif()
  endforeach()
  set(${result} ${dirlist})
endmacro()

macro(add_all_subdirectories curdir)
  sub_dir_list(SUBDIRS ${curdir})
  foreach(subdir ${SUBDIRS})
    add_subdirectory(${curdir}/${subdir})
  endforeach()
endmacro()